name: Update draft specification
on:
  workflow_dispatch:
  push:
    branches: draft

jobs:
  build-draft:
    name: Make draft spec release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@3105fb18c05ddd93efea5f9e0bef7a03a6e9e7df
      with:
        python-version: 3.x

    - name: Find pip cache dir
      id: pip-cache
      run: echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6
      with:
        # Use the os dependent pip cache directory found above
        path: ${{ steps.pip-cache.outputs.dir }}
        # A match with 'restore-keys' is used as fallback
        key: ${{ runner.os }}-pip-

    - name: Clone
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: Build specification
      run: |
        python -m pip install bikeshed
        mkdir build && cd build
        make -f ../Makefile draft

    - name: Switch branch
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        ref: gh-pages
        clean: false

    - name: Push generated specification
      run: |
        git config user.name "TUF Specification Automation"
        git config user.email theupdateframework@googlegroups.com
        rm -fr draft
        mv build/* .
        rmdir build
        git add .
        git commit -m "Publish latest draft specification"
        git push
