# .github/workflows/pr-push.yml
name: CI
on:
  pull_request: {}
  push:
    branches: [bs]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v1
        with:
          GH_PAGES_BRANCH: gh-pages
          SOURCE: tuf-spec.md
          TOOLCHAIN: bikeshed
          # FIXME: waiting for https://github.com/validator/validator/commit/b57b8d06e399a5bd07027906149b8b9700bac210 to land.
          VALIDATE_MARKUP: false
